### PR TITLE
[CJE-2213 cont’d] Update free-license, if present, to 7.0 tombstone

### PR DESCRIPTION
**Pull request by jglick**
Testing:
- [X] `free-license` not installed if it was not installed before (CJOC client, eval license)
- [ ] ~~upgraded if installed on an earlier LTS~~

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Note that the free license does not work at all on 1.609.1:

bq. Signature verification failed in update site &#039;cloudbees-proprietary&#039; <a href='#' class='showDetails'>(show details)</a><pre style='display:none'>java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors</pre>

so I am trying to install on 1.580.3 and then test the upgrade from there.

**Comment by jglick** [comment]
Added CB Registration plugin, though even in 1.580.3 the registration bar gets hidden by the Jenkins crumb bar unless you set the browser zoom level to 250% (no more, no less).

That did not add `free-license`. So I installed `cloudbees-plugin-gateway`, which has a similar UI issue with the crumb bar, but anyway after restart Jenkins was hosed:

```
INFO: Prepared all plugins
… hudson.ExtensionFinder$GuiceFinder <init>
SEVERE: Failed to create Guice container from all the plugins
com.google.inject.internal.guava.collect.$ComputationException: java.lang.NoClassDefFoundError: com/cloudbees/plugins/registration/CloudBeesUserAccountSelection
    at com.google.inject.internal.guava.collect.$ComputingConcurrentHashMap$ComputingMapAdapter.get(ComputingConcurrentHashMap.java:397)
    at …
    at com.cloudbees.jenkins.plugins.license.EntitlementChecker.all(EntitlementChecker.java:34)
    at com.cloudbees.jenkins.plugins.license.PluginImpl.postInitialize(PluginImpl.java:31)
    at hudson.PluginManager$2$1$2.run(PluginManager.java:386)
    at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
    at jenkins.model.Jenkins$7.runTask(Jenkins.java:886)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/cloudbees/plugins/registration/CloudBeesUserAccountSelection
    at …
Caused by: java.lang.ClassNotFoundException: com.cloudbees.plugins.registration.CloudBeesUserAccountSelection
    at …
```

So @stephenc I am not sure what to do with this, since I cannot even get the precondition working.

**Comment by jglick** [comment]
After deleting all `cloudbees-*` plugins, leaving only `free-license`, I can finally boot Jenkins. But maybe I should start from scratch having only installed `free-license` to begin with.

**Comment by jglick** [comment]
Nope, you can only get `free-license` if you install `cloudbees-plugin-gateway`. And if you do that, Jenkins 1.580.3 cannot restart.

**Comment by oleg-nenashev** [comment]
:+1: as far as I understand it

**Comment by stephenc** [comment]
:+1:

**Pull request merged**
